name: Build & Scan Container Image v1.3.0

on:
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  build_scan:
    name: Build And Scan Container Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v4

      - name: Set up docker build prereqs (Buildx)
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: src
          push: false
          tags: app:latest
          load: true

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: "ap-northeast-1"
          role-to-assume: "arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/gha-inspector-scan-role"

      - name: Scan built image with Inspector
        uses: aws-actions/vulnerability-scan-github-action-for-amazon-inspector@v1.3.0
        id: inspector
        with:
          artifact_type: 'container'
          artifact_path: 'app:latest' # make sure this matches the image you built
          display_vulnerability_findings: "enabled"
          critical_threshold: 1
          high_threshold: 1
          medium_threshold: 1
          low_threshold: 1
          other_threshold: 1

      # - name: Fail job if vulnerability threshold is exceeded
      #   run: exit ${{ steps.inspector.outputs.vulnerability_threshold_exceeded }}
